var jsonLivros = [{
    id: 0,
    titulo: '',
    urlImg: '',
    urlImgInfo: '',
    genero: '',
    subgenero: '',
    trechodoLivro: '',
    comentario1: '',
    comentario2: '',
}];

jsonLivros = [{
    id: 1,
    titulo: 'O Fim da Eternidade -  por Isaac Asimov',
    urlImg: 'oFimdoAmanha.jpg',
    urlImgInfo: 'oFimdaEternidade.png',
    genero: 'Ficção Científica',
    subgenero: 'Viagem no tempo',
    trechodoLivro: 'Acima de tudo, um Técnico deve ser um desapaixonado. A Mudança de Realidade iniciada por ele pode afetar a vida de cinquenta bilhões de pessoas. Cerca de um milhão dessas pessoas talvez sejam tão drasticamente afetadas que poderão ser consideradas novos indivíduos. Sob essas condições, atitudes emocionais constituem uma séria desvantagem.',
    comentario1: '"Um livro atemporal, feito para emocionar."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 2,
    titulo: 'Eu, Robô -  por Isaac Asimov',
    urlImg: 'euRobo.jpg',
    urlImgInfo: 'Eu, Robô.png',
    genero: 'Ficção Científica',
    subgenero: 'Cyberpunk',
    trechodoLivro: 'As pessoas dizem: “Está na cara”. Mas que partes da sua cara você consegue ver, a não ser que alguém lhe mostre um espelho? <br> Pode-se provar qualquer coisa que se queira com a razão friamente lógica... se forem escolhidos os postulados apropriados.',
    comentario1: '"Verdadeiro marco na história da ficção científica."<br> - THE NEW YORK TIMES',
    comentario2: '“Uma  verdadeira obra-prima da ficção científica.”<br> - THE GUARDIAN',
},
{
    id: 3,
    titulo: 'A Guerra dos Tronos : As Crônicas de Gelo e Fogo -  por George R. R. Martin',
    urlImg: 'AGuerrado Tronos.jpg',
    urlImgInfo: 'AGuerrado Tronos.png',
    genero: 'Fantasia',
    subgenero: 'Alta fantasia',
    trechodoLivro: 'Nunca se esqueça do que é, porque é certo que o mundo não se esquecerá. Faça disso sua força. Assim, não poderá ser nunca a sua fraqueza. Arme-se com essa lembrança, e ela nunca poderá ser usada para magoá-lo.',
    comentario1: '"A guerra dos tronos é a maior obra de fantasia desde que Bilbo encontrou o Anel."<br> - SF Reviews   ',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 4,
    titulo: 'Duna -   por Frank Herbert',
    urlImg: 'duna.jpg',
    urlImgInfo: 'duna.png',
    genero: 'Ficção Científica',
    subgenero: 'Space Opera',
    trechodoLivro: 'Não se pode entender um processo interrompendo-o. O entendimento precisa acompanhar o fluxo do processo, tem de se juntar a ele e fluir com ele.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 5,
    titulo: 'Neuromancer -  por William Gibson',
    urlImg: 'Neuromancer.jpg',
    urlImgInfo: 'oFimdaEternidade.png',
    genero: 'Ficção Científica',
    subgenero: 'Cyberpunk',
    trechodoLivro: 'Night City era como uma experiência malsucedida de darwinismo social, projetada por um pesquisador entediado que não tirava o dedo do botão de fast-forward.x',
    comentario1: '"Esta obra distópica, antevê, de modo muito preciso, vários aspectos fundamentais da sociedade atual e de sua relação com a tecnologia."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 6,
    titulo: '1984  - por George Orwell',
    urlImg: '1984.jpg',
    urlImgInfo: 'oFimdaEternidade.png',
    genero: 'Ficção Científica',
    subgenero: 'Universo Paralelo',
    trechodoLivro: 'Você não percebe que o verdadeiro objetivo do Novidioma é estreitar o limite do pensamento? No final, vamos tornar o crime de pensamento literalmente impossível, porque não vão existir palavras pelas quais expressá-lo.',
    comentario1: '"O maior escritor do século XX."<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 7,
    titulo: 'Count Zero  -  por William Gibson',
    urlImg: 'CountZero.jpg',
    urlImgInfo: 'oFimdaEternidade.png',
    genero: 'Ficção Científica',
    subgenero: 'Cyberpunk',
    trechodoLivro: 'E, por um instante, ela olhou diretamente para aqueles olhos azuis suaves e soube, com uma certeza instintiva de mamífero, que os excessivamente ricos não eram mais nem remotamente humanos.',
    comentario1: '"Nesse cenário frenético e superconectado, Gibson conseguiu criar um universo incrivel"<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 8,
    titulo: 'Mona Lisa Overdrive  - por William Gibson',
    urlImg: 'MonalisaOverdrive.jpg',
    urlImgInfo: 'oFimdaEternidade.png',
    genero: 'Ficção Científica',
    subgenero: 'Cyberpunk',
    trechodoLivro: '“A matrix tem suas raízes em games de fliperama primitivos”, disse uma voz em off, “nos primeiros programas gráficos e experiências militares com plugues cranianos.”',
    comentario1: '"O maior escritor do século XX."<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 9,
    titulo: 'Blade Runner  - por Philip K. Dick',
    urlImg: 'BladeRunner.jpg',
    urlImgInfo: 'oFimdaEternidade.png',
    genero: 'Ficção Científica',
    subgenero: 'Cyberpunk',
    trechodoLivro: 'Empatia, evidentemente, existia apenas na comunidade humana, ao passo que inteligência em qualquer grau poderia ser encontrada em todo filo ou ordem biológica, incluindo os aracnídeos.',
    comentario1: '"Atemporal, esse é o livro que originou um dos maiores filmes do cinema sci-fi."<br> - Observer',
    comentario2: '“Obra mais popular de Philip K. Dick, Blade Runner moldou parte do universo cyberpunk que conhecemos hoje. ”<br> - New York Review of Books',
},
{
    id: 10,
    titulo: 'As correntes do espaço  - por Isaac Asimov',
    urlImg: 'AsCorrentesdoEspaço.jpeg',
    urlImgInfo: 'oFimdaEternidade.png',
    genero: 'Ficção Científica',
    subgenero: 'Império Galáctico',
    trechodoLivro: 'Você não percebe que o verdadeiro objetivo do Novidioma é estreitar o limite do pensamento? No final, vamos tornar o crime de pensamento literalmente impossível, porque não vão existir palavras pelas quais expressá-lo.',
    comentario1: '"Aventura complexa com temas anti-racistas"<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 11,
    titulo: 'O Senhor dos Anéis: A Sociedade do Anel - por J.R.R. Tolkien',
    urlImg: 'ASociedadedoAnel.jpg',
    urlImgInfo: 'oFimdaEternidade.png',
    genero: 'Fantasia',
    subgenero: 'Alta fantasia',
    trechodoLivro: 'Não conheço a metade de vocês a metade do que gostaria; e gosto de menos da metade de vocês a metade do que merecem.',
    comentario1: '"O maior escritor do século XX."<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 12,
    titulo: 'O Senhor dos Anéis: As duas torres  - por J.R.R. Tolkien',
    urlImg: 'AsDuasTorres.jpg',
    urlImgInfo: 'oFimdaEternidade.png',
    genero: 'Fantasia',
    subgenero: 'Alta fantasia',
    trechodoLivro: 'O bem e o mal não mudaram desde antanho; nem são uma coisa entre os Elfos e os Anãos e outra entre os Homens. É papel do homem distingui-los, tanto na Floresta Dourada quanto em sua própria casa.',
    comentario1: '"O maior escritor do século XX."<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 13,
    titulo: 'O Senhor dos Anéis: O retorno do rei - por J.R.R. Tolkien',
    urlImg: 'O RetornodoRei.jpg',
    urlImgInfo: 'oFimdaEternidade.png',
    genero: 'Fantasia',
    subgenero: 'Alta fantasia',
    trechodoLivro: 'Você não percebe que o verdadeiro objetivo do Novidioma é estreitar o limite do pensamento? No final, vamos tornar o crime de pensamento literalmente impossível, porque não vão existir palavras pelas quais expressá-lo.',
    comentario1: '"O maior escritor do século XX."<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 14,
    titulo: 'O Mago Aprendiz. A Saga do Mago - Livro Um',
    urlImg: 'magoAprendiz.jpg',
    urlImgInfo: 'magoAprendiz.png',
    genero: 'Fantasia',
    subgenero: 'Alta fantasia',
    trechodoLivro: 'Todos os extremos, exceto a devoção extrema ao Inimigo, devem ser encorajados. <br> “Vejo agora que desperdicei a maior parte da minha vida sem fazer o que deveria nem o que desejava.',
    comentario1: '"Se Agatha Christie e James Joyce tivesem um filho literário bastardo, seria estre livro "<br> - Daily Telegraph',
    comentario2: '“Uma estreia emocionante! Definitivamente, é o surgimento de um grande talento',
},
{
    id: 15,
    titulo: 'Harry Potter e a Pedra Filosofal - Livro Um',
    urlImg: 'HarryPottereaPedraFilosofal.jpg',
    urlImgInfo: 'HarryPottereaPedraFilosofal.png',
    genero: 'Fantasia',
    subgenero: 'Baixa fantasia',
    trechodoLivro: 'Mas, daquele momento em diante, Hermione Granger tornou-se amiga dos dois. Há coisas que não se pode fazer junto sem acabar gostando um do outro, e derrubar um trasgo montanhês de quase quatro metros de altura é uma dessas coisas..',
    comentario1: 'Harry Potter e a Pedra Filosofal é o primeiro volume da série que reenventou a fantasia"<br> - Daily Telegraph',
    comentario2: 'Um surgimento de um clássico!<br> - THE NEW YORK TIMES',
},
{
    id: 16,
    titulo: 'Harry Potter e a Câmara Secreta',
    urlImg: 'HarryPottereaCâmaraSecreta.jpg',
    urlImgInfo: 'HarryPottereaCâmaraSecreta.png',
    genero: 'Fantasia',
    subgenero: 'Baixa fantasia',
    trechodoLivro: 'São as nossas escolhas, Harry, que revelam o que realmente somos, muito mais do que as nossas qualidades. <br> A CÂMARA SECRETA FOI ABERTA. INIMIGOS DO HERDEIRO, CUIDADO.',
    comentario1: 'Harry Potter reenventou a fantasia"<br> - Daily Telegraph',
    comentario2: 'Um surgimento de um clássico! <br>- THE NEW YORK TIMES',
},
{
    id: 17,
    titulo: 'Harry Potter e o Prisioneiro de Azkaban',
    urlImg: 'HarryPottereoPrisioneirodeAzkaban.jpg',
    urlImgInfo: 'HarryPottereoPrisioneirodeAzkaban.png',
    genero: 'Fantasia',
    subgenero: 'Baixa fantasia',
    trechodoLivro: 'O Sr. Aluado apresenta seus cumprimentos ao Prof. Snape e pede que ele não meta seu nariz anormalmente grande no que não é de sua conta..',
    comentario1: 'Harry Potter reenventou a fantasia"<br> - Daily Telegraph',
    comentario2: 'Um surgimento de um clássico!<br> - THE NEW YORK TIMES',
},
{
    id: 18,
    titulo: 'Harry Potter e o Cálice de Fogo',
    urlImg: 'HarryPottereoCálicedeFogo.jpg',
    urlImgInfo: 'HarryPottereoCálicedeFogo.png',
    genero: 'Fantasia',
    subgenero: 'Baixa fantasia',
    trechodoLivro: 'Se você quer saber como um homem é veja como ele trata os inferiores, e não os seus iguais.',
    comentario1: 'Harry Potter reenventou a fantasia"<br> - Daily Telegraph',
    comentario2: 'Um surgimento de um clássico!<br> - THE NEW YORK TIMES',
},
{
    id: 19,
    titulo: 'Harry Potter e a Ordem da Fênix',
    urlImg: 'HarryPottereaOrdemdaFênix.jpg',
    urlImgInfo: 'HarryPottereaOrdemdaFênix.png',
    genero: 'Fantasia',
    subgenero: 'Baixa fantasia',
    trechodoLivro: 'A sede da Ordem da Fênix encontra-se no largo Grimmauld, número doze, Londres.',
    comentario1: 'Harry Potter reenventou a fantasia"<br> - Daily Telegraph',
    comentario2: 'Um surgimento de um clássico! <br>- THE NEW YORK TIMES',
},
{
    id: 20,
    titulo: 'Jogador número um',
    urlImg: 'JogadorNúmeroUm.jpg',
    urlImgInfo: 'JogadorNúmeroUm.png',
    genero: 'Ficção Científica',
    subgenero: 'Universo Paralelo',
    trechodoLivro: 'A sede da Ordem da Fênix encontra-se no largo Grimmauld, número doze, Londres.',
    comentario1: 'Uma mistura de A Fantática Fábrica de Chocolate e Matrix <br> - USA Today',
    comentario2: 'Uma obra-prima geek! - Rolling Stone',
},
{
    id: 21,
    titulo: 'Pedra no Céu: Qualquer planeta é a Terra para aqueles que nele vive',
    urlImg: 'PedranoCéu.jpg',
    urlImgInfo: 'JogadorNúmeroUm.png',
    genero: 'Ficção Científica',
    subgenero: 'Império Galático',
    trechodoLivro: 'Você não percebe que o verdadeiro objetivo do Novidioma é estreitar o limite do pensamento? No final, vamos tornar o crime de pensamento literalmente impossível, porque não vão existir palavras pelas quais expressá-lo.',
    comentario1: '"Aventura complexa com temas anti-racistas"<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 22,
    titulo: 'Poeira de estrelas',
    urlImg: 'Poeira de estrelas.png',
    urlImgInfo: 'JogadorNúmeroUm.png',
    genero: 'Ficção Científica',
    subgenero: 'Império Galático',
    trechodoLivro: 'Você não percebe que o verdadeiro objetivo do Novidioma é estreitar o limite do pensamento? No final, vamos tornar o crime de pensamento literalmente impossível, porque não vão existir palavras pelas quais expressá-lo.',
    comentario1: '"Aventura complexa com temas anti-racistas"<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 23,
    titulo: 'Fundação e Império',
    urlImg: 'FundaçãoeImpério.jpg',
    urlImgInfo: 'JogadorNúmeroUm.png',
    genero: 'Ficção Científica',
    subgenero: 'Império Galático',
    trechodoLivro: 'Você não percebe que o verdadeiro objetivo do Novidioma é estreitar o limite do pensamento? No final, vamos tornar o crime de pensamento literalmente impossível, porque não vão existir palavras pelas quais expressá-lo.',
    comentario1: '"Aventura complexa com temas anti-racistas"<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 24,
    titulo: 'Segunda Fundação',
    urlImg: 'SegundaFundação.jpg',
    urlImgInfo: 'JogadorNúmeroUm.png',
    genero: 'Ficção Científica',
    subgenero: 'Império Galático',
    trechodoLivro: 'Você não percebe que o verdadeiro objetivo do Novidioma é estreitar o limite do pensamento? No final, vamos tornar o crime de pensamento literalmente impossível, porque não vão existir palavras pelas quais expressá-lo.',
    comentario1: '"Aventura complexa com temas anti-racistas"<br> - Observer',
    comentario2: '“Obra-prima terminal de Orwell, 1984 é uma leitura absorvente e indispensável para a compreensão da história moderna.”<br> - New York Review of Books',
},
{
    id: 25,
    titulo: 'Messias de Duna',
    urlImg: 'MessiasdeDuna.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Ficção Científica',
    subgenero: 'Space Opera',
    trechodoLivro: 'São treinados para acreditar, não para conhecer. A fé pode ser manipulada. Só o conhecimento é perigoso.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 26,
    titulo: 'Filhos de Duna',
    urlImg: 'FilhosdeDuna.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Ficção Científica',
    subgenero: 'Space Opera',
    trechodoLivro: 'Você não percebe que o verdadeiro objetivo do Novidioma é estreitar o limite do pensamento? No final, vamos tornar o crime de pensamento literalmente impossível, porque não vão existir palavras pelas quais expressá-lo.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 27,
    titulo: 'Imperador Deus de Duna',
    urlImg: 'ImperadorDeusdeDuna.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Ficção Científica',
    subgenero: 'Space Opera',
    trechodoLivro: 'Você não percebe que o verdadeiro objetivo do Novidioma é estreitar o limite do pensamento? No final, vamos tornar o crime de pensamento literalmente impossível, porque não vão existir palavras pelas quais expressá-lo.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 28,
    titulo: 'Hereges de Duna',
    urlImg: 'HeregesdeDuna.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Ficção Científica',
    subgenero: 'Space Opera',
    trechodoLivro: 'Você não percebe que o verdadeiro objetivo do Novidioma é estreitar o limite do pensamento? No final, vamos tornar o crime de pensamento literalmente impossível, porque não vão existir palavras pelas quais expressá-lo.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 29,
    titulo: 'Chronos. Viajantes do Tempo',
    urlImg: 'ChronosViajantesdoTempo.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Ficção Científica',
    subgenero: 'Universo Paralelo',
    trechodoLivro: 'Se uma pessoa procedeu mal, arrependa-se, faça as reparações que puder e trate de comportar-se melhor na próxima vez. Não deve, de modo nenhum, pôr-se a remoer suas más ações. Espojar-se na lama não é a melhor maneira de ficar limpo.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 30,
    titulo: 'Battle Royale',
    urlImg: 'Battle Royale.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Ficção Científica',
    subgenero: 'Universo Paralelo',
    trechodoLivro: 'Se uma pessoa procedeu mal, arrependa-se, faça as reparações que puder e trate de comportar-se melhor na próxima vez. Não deve, de modo nenhum, pôr-se a remoer suas más ações. Espojar-se na lama não é a melhor maneira de ficar limpo.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 31,
    titulo: 'A fúria dos reis - por George R.R. Martin',
    urlImg: 'AFuriadosReis.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Fantasia',
    subgenero: 'Alta Fantasia',
    trechodoLivro: 'Nos livros antigos de Asshai está escrito que chegará um dia, após um longo verão, em que as estrelas sangrarão e o bafo frio da escuridão cairá, pesado, sobre o mundo. Nessa hora de terror, um guerreiro retirará do fogo uma espada em chamas. E essa espada será a Luminífera, a Espada Vermelha dos Heróis, e aquele que a pegar será Azor Ahai renascido, e a escuridão fugirá perante ele.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 32,
    titulo: 'A tormenta de espadas - por George R.R. Martin',
    urlImg: 'ATormentadeEspadas.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Fantasia',
    subgenero: 'Alta Fantasia',
    trechodoLivro: 'Lembre-se. Para ir para o Norte, deve viajar para o Sul. Para alcançar o Oeste, tem de ir para Leste. Para ir em frente, deve voltar para trás, e para tocar a luz, tem de passar sob a sombra.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 33,
    titulo: 'O Festim dos Corvos - por George R.R. Martin',
    urlImg: 'OFestimdosCorvos.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Fantasia',
    subgenero: 'Alta Fantasia',
    trechodoLivro: 'As palavras são como flechas, Arianne. Depois de disparadas, não podem ser chamadas de volta.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 34,
    titulo: 'A dança dos dragões - por George R.R. Martin',
    urlImg: 'ADançadosDragões.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Fantasia',
    subgenero: 'Alta Fantasia',
    trechodoLivro: 'As velas nos vidros estão queimando. Logo virá a égua descorada e, depois dela, os outros. A lula-gigante e a chama escura, o leão e o grifo, o filho do sol e o dragão do pantomimeiro. Não acredite em nenhum deles. Lembre-se dos Imortais. Cuidado com o senescal perfumado.',
    comentario1: '"Testemunhe um clássico absoluto da ficção científica."<br> - THE INDEPENDENT',
    comentario2: '“Uma obra-prima de um esplendor pungente... desoladora, absoluta e completamente brilhante.”<br> - THE GUARDIAN',
},
{
    id: 35,
    titulo: 'O ladrão de raios -  por Rick Riordan',
    urlImg: 'OLadrãodeRaios.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Fantasia',
    subgenero: 'Fantasia Mitológica',
    trechodoLivro: 'Você se saiu bem, Perseu. Não me entenda mal. O que quer que ainda faça, saiba que você é meu. Você é um verdadeiro filho do deus do mar.',
    comentario1: 'Tem um ritmo perfeito<br> - THE INDEPENDENT',
    comentario2: 'Com momentos eletrizantes seguindo-se uns aos outros como batimentos, e um mistério atrás do outro”<br> - THE GUARDIAN',
},
{
    id: 36,
    titulo: 'O mar de monstros -  por Rick Riordan',
    urlImg: 'OMardeMonstros.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Fantasia',
    subgenero: 'Fantasia Mitológica',
    trechodoLivro: 'Você se saiu bem, Perseu. Não me entenda mal. O que quer que ainda faça, saiba que você é meu. Você é um verdadeiro filho do deus do mar.',
    comentario1: 'Mistura inteligente de mitologia grega  com personagens adolescentes contemporâneos, em uma aventura repleta de emoção<br> - BOOKLIST',
    comentario2: 'Com momentos eletrizantes seguindo-se uns aos outros como batimentos, e um mistério atrás do outro”<br> - THE GUARDIAN',
},
{
    id: 37,
    titulo: 'A maldição do titã -  por Rick Riordan',
    urlImg: 'AMaldiçãodoTitã.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Fantasia',
    subgenero: 'Fantasia Mitológica',
    trechodoLivro: 'Os sonhos são como um podcast, Fazendo download da verdade em meus ouvidos, Eles me dizem coisas muito legais.Os sonhos são como um podcast, Fazendo download da verdade em meus ouvidos, Eles me dizem coisas muito legais.',
    comentario1: 'Tem um ritmo perfeito<br> - THE INDEPENDENT',
    comentario2: 'Com momentos eletrizantes seguindo-se uns aos outros como batimentos, e um mistério atrás do outro”<br> - THE GUARDIAN',
},
{
    id: 38,
    titulo: 'A batalha do labirinto -  por Rick Riordan',
    urlImg: 'ABatalhadoLabirinto.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Fantasia',
    subgenero: 'Fantasia Mitológica',
    trechodoLivro: 'Annabeth me olhou, furiosa, como se fosse me dar um soco. E então fez algo que me surpreendeu ainda mais. Ela me beijou.',
    comentario1: 'Tem um ritmo perfeito<br> - THE INDEPENDENT',
    comentario2: 'Com momentos eletrizantes seguindo-se uns aos outros como batimentos, e um mistério atrás do outro”<br> - THE GUARDIAN',
},
{
    id: 39,
    titulo: 'O último olimpiano -  por Rick Riordan',
    urlImg: 'OUltimoOlimpiano.jpg',
    urlImgInfo: 'ASociedadedoAnel.png',
    genero: 'Fantasia',
    subgenero: 'Fantasia Mitológica',
    trechodoLivro: 'Se você está indo do Central Park para o centro da cidade, meu conselho é que vá de metrô. Porcos voadores são mais rápidos, mas bem mais perigosos.',
    comentario1: 'Tem um ritmo perfeito<br> - THE INDEPENDENT',
    comentario2: 'Com momentos eletrizantes seguindo-se uns aos outros como batimentos, e um mistério atrás do outro”<br> - THE GUARDIAN',
},
];


function mostrar(idLivro) {
    for (var i = 0; i < jsonLivros.length; i++) {
        if (jsonLivros[i].id == idLivro) {
            console.log(jsonLivros[i].titulo);


            container.style = "display: none";
            mostrarLivro.style = "display: block";


            titulo.innerHTML = jsonLivros[i].titulo;
            urlImg.src = "./img/imgCapaLivros/" + jsonLivros[i].urlImg;
            urlImgInfo.src = "./img/imgInfoLivros/" + jsonLivros[i].urlImgInfo;
            genero.innerHTML = jsonLivros[i].genero;
            subgenero.innerHTML = jsonLivros[i].subgenero;
            trechodoLivro.innerHTML = jsonLivros[i].trechodoLivro;
            comentario1.innerHTML = jsonLivros[i].comentario1;
            comentario2.innerHTML = jsonLivros[i].comentario2;
        }
    }
}